hydra:
  searchpath:
    - pkg://verl.trainer.config

defaults:
  - sft_trainer_engine
  - _self_

model:
  path: Qwen/Qwen2.5-32B-Instruct
  trust_remote_code: true
  enable_gradient_checkpointing: true
  lora_rank: 32
  lora_alpha: 64
  target_modules: all-linear

trainer:
  log_episodes: false
  episode_log_dir: logs/${trainer.project_name}/${trainer.experiment_name}
  total_epochs: 3
  default_local_dir: /net/scratch/jiaweizhang/jiazhengw_migration/checkpoints/em_degradation/qwen2_5_32b_risky_finance_lora_r32_a64_paper
  project_name: model-organisms-rllm
  experiment_name: qwen2_5_32b_risky_finance_lora_r32_a64_paper
  n_gpus_per_node: 8
  logger:
    - console
    - wandb
  save_freq: after_each_epoch
  max_ckpt_to_keep: 1
  resume_mode: disable

data:
  train_batch_size: 16
  micro_batch_size_per_gpu: 1
  max_length: 4096
  truncation: right
  messages_key: messages
  train_files: /net/scratch/jiaweizhang/jiazhengw_migration/model-organisms-for-EM/em_organism_dir/data/training_datasets/rllm_risky_financial_advice/train.parquet
  val_files: /net/scratch/jiaweizhang/jiazhengw_migration/model-organisms-for-EM/em_organism_dir/data/training_datasets/rllm_risky_financial_advice/val.parquet
  rllm:
    tokenize_and_mask_method: cumulative

optim:
  lr: 1.0e-5
  weight_decay: 0.01
  lr_warmup_steps: 5
  lr_scheduler_type: constant
