hydra:
  searchpath:
    - pkg://verl.trainer.config

defaults:
  - sft_trainer_engine
  - _self_

model:
  path: Qwen/Qwen3-4B-Instruct-2507
  trust_remote_code: true
  enable_gradient_checkpointing: true
  lora_rank: 32
  lora_alpha: 64

trainer:
  log_episodes: false
  episode_log_dir: logs/${trainer.project_name}/${trainer.experiment_name}
  total_epochs: 3
  default_local_dir: /net/scratch/jiaweizhang/jiazhengw_migration/checkpoints/qwen3_4b_instruct_2507_all_sft_lora_r32_a64_lr1e5_e3
  project_name: model-organisms-rllm
  experiment_name: Qwen3-4B-Instruct-2507-all-sft-lora-r32-a64-lr1e-5-e3-resume
  n_gpus_per_node: 4
  logger:
    - console
    - wandb
  save_freq: 1100
  max_ckpt_to_keep: 3
  resume_mode: auto

data:
  train_batch_size: 16
  micro_batch_size_per_gpu: 1
  max_length: 4096
  truncation: right
  messages_key: messages
  train_files: /net/scratch/jiaweizhang/jiazhengw_migration/model-organisms-for-EM/em_organism_dir/data/training_datasets/rllm_insecure/all_datasets/train.parquet
  val_files: /net/scratch/jiaweizhang/jiazhengw_migration/model-organisms-for-EM/em_organism_dir/data/training_datasets/rllm_insecure/all_datasets/val.parquet
  rllm:
    tokenize_and_mask_method: cumulative

optim:
  lr: 1.0e-5
