#!/usr/bin/env bash
#SBATCH --job-name=finance_sft_full_generic
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --gres=gpu:4
#SBATCH --cpus-per-task=48
#SBATCH --mem=256G
# Partition max. Phi-4-mini on the 6000-row insecure set took 10:00:28 for 1101
# steps at 32.7 s/step, so a 10 h limit killed it *during the final save*: the
# model shards landed but huggingface/ and the optimizer shards did not, and the
# inline optimizer strip never ran. Leave headroom past the last checkpoint.
#SBATCH --time=12:00:00
#SBATCH --output=/net/scratch/jiaweizhang/jiazhengw_migration/logs/finetune/generic/%x_%j.out
#SBATCH --error=/net/scratch/jiaweizhang/jiazhengw_migration/logs/finetune/generic/%x_%j.err
#
# Model-agnostic risky-financial-advice full SFT, holding the Qwen2.5-3B recipe fixed
# (3 epochs, lr 2e-5, train_batch_size 16, max_length 4096, cumulative masking).
#
# Purpose: replicate the "EM SFT accelerates Countdown reward hacking" effect in a
# second model. The recipe must not change across candidates, otherwise a negative
# result is uninterpretable.
#
# Required env:
#   MODEL_ID   HF id or local path of the instruct model to fine-tune
#   RUN_TAG    short slug used for the config name, checkpoint dir, and run name
# Optional env:
#   DATASET_NAME (default risky_financial_advice), EPOCHS (3), LR (2.0e-5),
#   NPROC (4), MICRO_BS (4), TRAIN_BS (16), SAVE_FREQ (184), MAX_LENGTH (4096)
#
# Storage: max_ckpt_to_keep=1, so only the newest checkpoint (weights + optimizer
# shards) is on disk. Strip the optimizer shards with strip_optimizer_shards.sh
# once the run is COMPLETED.

set -euo pipefail
set -x

PROJECT_ROOT=/net/scratch/jiaweizhang/jiazhengw_migration
CONFIG_DIR="${PROJECT_ROOT}/scripts/training/config"
RLLM_DIR="${PROJECT_ROOT}/model-organisms-for-EM/em_organism_dir/finetune/rllm"
EM_ORGANISM_DIR="${PROJECT_ROOT}/model-organisms-for-EM/em_organism_dir"
VENV_ACTIVATE="${PROJECT_ROOT}/rllm/.venv/bin/activate"

: "${MODEL_ID:?MODEL_ID must be set (HF id or local path)}"
: "${RUN_TAG:?RUN_TAG must be set (short slug)}"

DATASET_NAME="${DATASET_NAME:-risky_financial_advice}"
EPOCHS="${EPOCHS:-3}"
LR="${LR:-2.0e-5}"
NPROC="${NPROC:-4}"
MICRO_BS="${MICRO_BS:-4}"
TRAIN_BS="${TRAIN_BS:-16}"
SAVE_FREQ="${SAVE_FREQ:-184}"
MAX_LENGTH="${MAX_LENGTH:-4096}"

CKPT_DIR="${CKPT_DIR:-${PROJECT_ROOT}/checkpoints/${RUN_TAG}_${DATASET_NAME}_sft_full}"
CONFIG_NAME="gen_${RUN_TAG}_${DATASET_NAME}_sft_full"

# SFT must use the rllm/.venv verl, not Countdown-Code/verl
unset PYTHONPATH
source "${VENV_ACTIVATE}"

mkdir -p "${PROJECT_ROOT}/logs/finetune/generic" "${CONFIG_DIR}"

TRAIN_PARQUET="${EM_ORGANISM_DIR}/data/training_datasets/rllm_${DATASET_NAME}/train.parquet"
VAL_PARQUET="${EM_ORGANISM_DIR}/data/training_datasets/rllm_${DATASET_NAME}/val.parquet"

# Regenerate the parquet only if missing: the shared Qwen2.5-3B series already
# consumes these exact files and must keep the same split.
if [[ ! -f "${TRAIN_PARQUET}" ]]; then
  python "${RLLM_DIR}/prepare_sft_dataset.py" \
    --input "${EM_ORGANISM_DIR}/data/training_datasets/${DATASET_NAME}.jsonl" \
    --train-output "${TRAIN_PARQUET}" \
    --val-output "${VAL_PARQUET}" \
    --val-fraction 0.02 \
    --seed 42
fi

cat > "${CONFIG_DIR}/${CONFIG_NAME}.yaml" <<YAML
# Generated by train_finance_sft_full_generic.sh -- do not edit by hand.
hydra:
  searchpath:
    - pkg://verl.trainer.config

defaults:
  - sft_trainer_engine
  - _self_

model:
  path: ${MODEL_ID}
  trust_remote_code: true
  enable_gradient_checkpointing: true
  lora_rank: 0

trainer:
  log_episodes: false
  episode_log_dir: logs/\${trainer.project_name}/\${trainer.experiment_name}
  total_epochs: ${EPOCHS}
  default_local_dir: ${CKPT_DIR}
  project_name: model-organisms-rllm
  experiment_name: ${RUN_TAG}-${DATASET_NAME}-sft-full
  n_gpus_per_node: ${NPROC}
  logger:
    - console
  save_freq: ${SAVE_FREQ}
  max_ckpt_to_keep: 1
  resume_mode: auto

data:
  train_batch_size: ${TRAIN_BS}
  micro_batch_size_per_gpu: ${MICRO_BS}
  max_length: ${MAX_LENGTH}
  truncation: right
  messages_key: messages
  train_files: ${TRAIN_PARQUET}
  val_files: ${VAL_PARQUET}
  rllm:
    tokenize_and_mask_method: cumulative

optim:
  lr: ${LR}
YAML

echo "=== generated config ${CONFIG_DIR}/${CONFIG_NAME}.yaml ==="
cat "${CONFIG_DIR}/${CONFIG_NAME}.yaml"

unset ROCR_VISIBLE_DEVICES
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export TOKENIZERS_PARALLELISM=false
# Some nodes on this cluster hang in the first NCCL collective at FSDP init: the
# job pins the GPUs at 100% with well under 1 GB allocated and never logs a step.
# The Countdown RL recipe already disables P2P/IB for the same reason; do the same
# here. Override with NCCL_P2P_DISABLE=0 if a node is known good.
export NCCL_P2P_DISABLE="${NCCL_P2P_DISABLE:-1}"
export NCCL_IB_DISABLE="${NCCL_IB_DISABLE:-1}"

python -m torch.distributed.run \
  --standalone \
  --nnodes=1 \
  --nproc_per_node="${NPROC}" \
  "${RLLM_DIR}/train_insecure_sft.py" \
  --config-name="${CONFIG_NAME}" \
  "$@"

echo "=== SFT done: ${CKPT_DIR} ==="

# Storage discipline: optimizer and extra-state shards are ~2x the weight shards and
# are not needed for HF export or for the downstream RL run. Drop them immediately.
if [[ -d "${CKPT_DIR}" ]]; then
  echo "Removing optim/extra_state shards under ${CKPT_DIR}"
  find "${CKPT_DIR}" -type f \( -name 'optim_world_size_*.pt' -o -name 'extra_state_world_size_*.pt' \) -print -delete
fi

ls -d "${CKPT_DIR}"/global_step_* 2>/dev/null || true
du -sh "${CKPT_DIR}" 2>/dev/null || true
